---
title: A scalable and flexible Cox proportional hazard model for high-dimensional survival prediction and functional selection
authors:
- name: Boyi Guo
  thanks: Corresponding authors \\email{boyiguo1@uab.edu}
  department: Department of Biostatistics
  affiliation: University of Alabama at Birmingham
  location: Birmingham, AL
- name: Byron C. Jaeger
  department: Department of Biostatistics and Data Science
  affiliation: Wake Forest School of Medicine
  location: Winston-Salem, NC
- name: AKM Fazlur Rahman
  department: Department of Biostatistics
  affiliation: University of Alabama at Birmingham
  location: Birmingham, AL  
- name: D. Leann Long
  department: Department of Biostatistics
  affiliation: University of Alabama at Birmingham
  location: Birmingham, AL 
- name: Nengjun Yi
  thanks: Corresponding authors \\email{nyi@uab.edu}
  department: Department of Biostatistics
  affiliation: University of Alabama at Birmingham
  location: Birmingham, AL
abstract: "Cox proportional hazard (PH) model is one of the most popular models in biomedical data analysis. There have been continuing efforts to improve the flexibility of such models for complex signal detection, for example, via additive functions. Nevertheless, the task to extend Cox additive models to accomodate high-dimensional data is nontrivial. When estimating additive functions, commonly used group sparse regularization may introduce excess smoothing shrinkage on additive functions, damaging predictive performance. Moreover, an “all-in-all-out” approach makes functional selection challenging to answer if nonlinear effects exist. We develop an additive Cox PH model to xxx. Notably, we impose a novel spike-and-slab LASSO prior that motivates the bi-level functional selection on additive functions. A scalable and deterministic algorithm, EM-Coordinate Descent, is designed for scalable model fitting. We compare the predictive and computational performance against state-of-the-art models in simulation studies and metabolomics data analysis. The proposed model is broadly applicable to various fields of research, e.g. genomics and population health, via freely available R package BHAM (https://boyiguo1.github.io/BHAM/)"
keywords: Cox Model; Spike-and-Slab; Scalable; Machine Learning; R Package;
output: 
  rticles::arxiv_article:
    keep_tex: true
    #citation_package: biblatex
#biblio-style: apa
bibliography: "references.bib"
header-includes: 
    - \usepackage{amsmath}
---

\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\tp}{*}
\newcommand{\simiid}{\overset{\text{iid}}{\sim}}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(targets)
library(xtable)

tar_load(manu_path)
# tar_load(sim_test_tab)
# tar_load(sim_test_viz)

```


```{r intro, child = "~/GitHub/Manuscript-BH_Additive_Cox/Manuscript/01-intro.Rmd"}
```

```{r method, child = "~/GitHub/Manuscript-BH_Additive_Cox/Manuscript/02-method.Rmd"}
```

```{r simulation, child="~/GitHub/Manuscript-BH_Additive_Cox/Manuscript/03-simulation.Rmd"}
```

```{r real_data, child="~/GitHub/Manuscript-BH_Additive_Cox/Manuscript/04-real_data.Rmd"}
```

```{r conclusion, child="~/GitHub/Manuscript-BH_Additive_Cox/Manuscript/05-conclusion.Rmd"}
```
\newpage


<!-- Tables and Figures start here -->
