---
bibliography: references.bib
---

\section{Discussion}

In this article, we introduce the two-part spike-and-slab LASSO prior to Cox additive models for high-dimensional survival data analysis. Specifically, the proposed spike-and-slab LASSO prior adopts the sparse penalty to select effective predictors and the smooth penalty to estimate the degree of smoothness of the underlying nonlinear function. This mechanism addresses the previous criticism that high-dimensional additive models without smooth penalty tends to oversmooth the estimate of the underlying linear function. Meanwhile, the two-part prior encourages a bi-level selection of each predictor, selection of effective predictors and distinguishing linear and nonlinear effects among predictors. In addition to the Bayesian hierarchical Cox additive model proposal, we develop a optimization-based algorithm to provide a scalable solution to fit the model. This substantially reduces computational demands in comparison to posterior approximation algorithms. Lastly, we implement the proposed model and fitting algorithm in a freely available R package \texttt{BHAM} via \url{https://github.com/boyiguo1/BHAM}, along with many other utility functions to support model specification, tuning, and diagnostic.

Similar to many machine learning algorithms that provides flexible modeling of complex signal, the proposed model requires no assumption checking prior to the model fitting. This is because the model can automatically choose from the linear or nonlinear forms for a predictor. Such decisions are data-driven, as the underlying penalty is locally adaptive, depending on the data. Nevertheless, we still encourage the authors relies on domain knowledge to decides variable selection, or construct more than one model when domain knownledge does not exist. [TODO: add a sentence on why, bi-level seleciton could include false positive component of the complex function. For example, when the underlying model include no linear component, e.g. $x^2$, the proposed model still tends to include a linear effect in the model.] This phenomenon is because of the effect hierarchy we impose on the prior structure. In other words, we encourage the model to include the linear component when the nonlinear effect is detected. A viable solution, is to consider the inclusion of the linear and nonlinear effect independent. Nevertheless, this could result in other intended consequences, for example xxxx. [TODO: double check with the GLM results]. Hence, our suggestion is to lean on the domain knowledge to decides, and also check the curve when the objective to use the model to conduct predictor selection.

In this article, we only shows the basic survival model without mentioning some other analytic problems likely to encounter in survival analysis, for example delayed entry, stratified Cox models. These analytic problems can be easily addressed and implemented under the current model framework. Another important extension of the proposed model is to model time varying effect. Such extension requires minimum modification: one can simply construct the additive function matrix for time, and multiply with the covariates. We see similar strategy was applied in \cite{wang2007}. In our future work, we attempt to expand the univariate additive function to multi-dimensional surface, for example via tensor product spline \cite{Wood2017}. Hence, the interaction effect between covariates can be modeled. Such complex functional covariates include domain-specific transofrmation and subject-specfic transformation (Cui, Crainiceanu, Leroux). Such modeling strategy have great potention in wearable devcies data analysis. 

In conclusion, we proposed a new Bayesian hierarchical model to address Cox additive model in high-dimensional settings, and provide a software implementation of the proposed model. The model fitting algorithm is easily scalable. THe provides xxx for clinical and molecular data analysis.
